### ISSUE TITLE
appuser

### ISSUE THREAD

**Issue by jhavens12** [arpanghosh8453/garmin-grafana#10]
It looks like in the example compose.yml file you keep the credentials in the /home/appuser directory - is there a reason it's not in the folder of the logged in user? I tried changing the compose file to reflect the logged in user's directory and the first step of getting the token works fine. When I try to stand up the compose file however, it still looks in the /home/appuser directory instead of the logged in users directory to authenticate.

`PermissionError: [Errno 13] Permission denied: '/home/appuser/.garminconnect/oauth1_token.json'`

I'm not sure if I'm supposed to change the directory to my logged in user in the docker file or not

**Comment by jhavens12** [comment]
More info:

`2025-04-15 14:43:38,780 - INFO - Trying to login to Garmin Connect using token data from directory '~/.garminconnect'...
2025-04-15 14:43:38,780 - WARNING - Session is expired or login information not present/incorrect. You'll need to log in again...login with your Garmin Connect credentials to generate them.
Enter Garminconnect Login e-mail: MYEMAIL
Enter Garminconnect password (characters will be visible): MYPASSWORD
MFA one-time code (via email or SMS): 123456
Traceback (most recent call last):
  File "/app/garmin-fetch.py", line 92, in garmin_login
    garmin.login(TOKEN_DIR)
  File "/usr/local/lib/python3.12/site-packages/garminconnect/__init__.py", line 231, in login
    self.garth.load(tokenstore)
  File "/usr/local/lib/python3.12/site-packages/garth/http.py", line 225, in load
    with open(os.path.join(dir_path, "oauth1_token.json")) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/appuser/.garminconnect/oauth1_token.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/garmin-fetch.py", line 687, in <module>
    garmin_obj = garmin_login()
                 ^^^^^^^^^^^^^^
  File "/app/garmin-fetch.py", line 108, in garmin_login
    garmin.garth.dump(TOKEN_DIR)
  File "/usr/local/lib/python3.12/site-packages/garth/http.py", line 209, in dump
    with open(os.path.join(dir_path, "oauth1_token.json"), "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/appuser/.garminconnect/oauth1_token.json'`

**Comment by TimTim74** [comment]
I've had the same problem. Since I was already running GarminDB with garth in a different project, I just copied the login-files from that to a local folder and changed the docker-compose:

`volumes:
      - ./garminconnect:/home/appuser/.garminconnect`

And that local folder contains the following files:
- oauth1_token.json
- oauth2_token.json
- gart_session

**Comment by arpanghosh8453** [comment]
Looks like it can't write to the container volume created. The volume is created by 

Try these two configuration and let me know if they work:

1. Create a `.garminconnect-tokens` folder inside your home folder. Then chown that folder to `1000:1000` or change the permission to `777`

Then use the following configuration - 

```yaml
services:
  garmin-fetch-data:
    restart: unless-stopped
    image: thisisarpanghosh/garmin-fetch-data:latest
    container_name: garmin-fetch-data
    depends_on:
      - influxdb
    volumes:
      - /home/your-username/.garminconnect-tokens:/home/appuser/.garminconnect # (persistant tokens storage) - you can use bind mounts as well (read troubleshooting)
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=influxdb_user # user should have read/write access to INFLUXDB_DATABASE
      - INFLUXDB_PASSWORD=influxdb_secret_password
      - INFLUXDB_DATABASE=GarminStats
      - UPDATE_INTERVAL_SECONDS=300 # Default update check interval is set to 5 minutes
      - LOG_LEVEL=INFO # change to DEBUG to get DEBUG logs
```

Alternatively, can you try running the same container as root user?

```yaml
services:
  garmin-fetch-data:
    restart: unless-stopped
    image: thisisarpanghosh/garmin-fetch-data:latest
    container_name: garmin-fetch-data
    user: root
    depends_on:
      - influxdb
    volumes:
      - /home/your-username/.garminconnect-tokens:/home/appuser/.garminconnect # (persistant tokens storage) - you can use bind mounts as well (read troubleshooting)
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=influxdb_user # user should have read/write access to INFLUXDB_DATABASE
      - INFLUXDB_PASSWORD=influxdb_secret_password
      - INFLUXDB_DATABASE=GarminStats
      - UPDATE_INTERVAL_SECONDS=300 # Default update check interval is set to 5 minutes
      - LOG_LEVEL=INFO # change to DEBUG to get DEBUG logs
 ```
