### ISSUE TITLE
Portainer Guide

### ISSUE THREAD

**Issue by w9925** [arpanghosh8453/garmin-grafana#4]
Could you please add an guide how to set it up in portainer?

**Comment by arpanghosh8453** [comment]
Never thought about this, but there can be two ways. 

- If you don't use MFA/2FA : Then it's simple, you can use the example stack without issues, just add the email and base64 encoded password as ENV variables. Read `3` in the [setup instructions](https://github.com/arpanghosh8453/garmin-grafana#install-with-docker-recommended)

- If you use 2FA/MFA : The one time code must be entered interactively when you run the initial container setup. So maybe use the compose stack example given with the two additional flags added the grafana-fetch-data container. Then maybe you can connect to the shell in the console tab of Portainer. I don't see any better way of running the stack with Portainer. I personally use [dockge](https://github.com/louislam/dockge) as it gives me the flexibility of compose without locking me in the Portainer environment. 
```yaml
services:
  your-service:
    image: your-image
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
```
