### ISSUE TITLE
[FEATURE] Multiple Garmin Users

### ISSUE THREAD

**Issue by kruemelro** [arpanghosh8453/garmin-grafana#96]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to view multiple Users in the Dashboard. Also i wan't to be able to compare some stats. 
You mentioned in [#18 ](https://github.com/arpanghosh8453/garmin-grafana/issues/18) you don't wan't to implement this. I think there is a much easier solution. Could you just add the Email Address from the Env Variable as Tag to all Metrics? 

So its possible to spin up one Instance of the Importer for each user and let them write to the same database. On the Dashboard we could use a variable to switch between the users. 

With this approach it would take much less ressources instead of spinning up multiple influxDBs and Grafana Dashboards

**Comment by arpanghosh8453** [comment]
Hello @kruemelro Thank you for opening this so I can explain this better. 

You do not need a whole new stack for each user by all means. You should have only one InfluxDB and Grafana instance. 

I don't think it's a good idea to keep two/multiple person's data under the same database name. Mind that a single InfluxDB instance can have multiple databases. I personally have 4 databases under the one running InfluxDB container. Check out [InfluxDB documentation](https://docs.influxdata.com/influxdb/v1/introduction/get-started/) how to create new databases (and give permission to users if you are enforcing authentication). The database name given in the Influxdb compose ENV variable is just for initial setup. Use can use additional command like `docker exec influxdb influx create database GarminStats-wife` or something on that line to create more databases under the same instance. 

Then simply spin up a new instance of the `garmin-fetch-data` (networking knowledge is important here - make sure they are under the same stack or connect then properly with docker networks so the new container can reach the original influxdb container - otherwise it will fail as `influxdb` hostname not resolved), with the DB name changed to the other database you just created as `INFLUXDB_DATABASE=GarminStats-wife. Keep the Host and port the same. Initialize the new instance like the old one with initial docker run to enter the username and password (+ 2FA code if applicable). Now when you run the containers, they will add data to their respective database. I believe this is the best way to have multi-user instance without any additional modification to the current codebase and you don't need to duplicate influxdb or Grafana containers. 

Then finally just add that new data source to Grafana, and you can clone the entire dashboard if you want for the other user(s). **Grafana allows mixed data sources for single panel**, so you can plot data from two databases and compare them with each other in the same panel like you wanted here. 

The advantage with this is you don't need to modify each panel with the additional tag for filtering like you originally wanted to (that will prevent you from future dashboard upgrades from this project) - while getting the best of both worlds. Also, there will be no chance of data mix-up and you can take backup of the data for individual person and archive it accordingly. 

Let me know if that makes sense. Thanks again.

**Comment by kruemelro** [comment]
I got your points and could understand the reason behind it. 
From a users point of view it's easier to just copy the importer part in the compose file and the system behinds do the "magic". 
So the user doesn't have to friggle with influx commands. Also the user doesn't have to keep multiple dashboards updated.

The variable and the filter could be implemented in the dashboard for all users. But of corse thats a design decision you have to make. 

I'm a SysAdmin and fine with both ways. But not all users have that level of knowledge. From my point of view it would be some work to change the tag and dashboard to get a better and easier user experience.

**Comment by arpanghosh8453** [comment]
@kruemelro But still, to setup the additional user, they will need to copy the garmin-fetch-data container config, change the names (to avoid name conflicts) and do the two docker runs for initialization, and I consider that tough for anyone not familiar with docker anyway. So definitely multi-user is not a easy thing with this project as there is no native support yet. And without that in place, I don't think it will be a good idea to add the user specific filter in the dashboard JSON. I also think you don't need to create a database beforehand and manage authentication if you are not enforcing authentication (as default with this project)

Maybe in this project becomes large enough and this gets enough request, I might try to see the best way to implement this for the less-tech savvy users. Then your suggestion might come handy - and I also thought about this before. But as it is right now, it's available with some tweaks as I mentioned above - but it requires docker knowledge. I can add the additional tag fairly quickly (which I will probably do soon as you requested), but I won't think availability of that will solve the common user's problem - who don't have a clear idea how the system works.

**Comment by kruemelro** [comment]
Yeah, i think you're right. Users wo are able to spin this up should also able to do the needed commands. 

Should i leave the request open as a request tracker? So everyone wo want's this could just give a thump up on the request

**Comment by arpanghosh8453** [comment]
@kruemelro, Precisely, as they need to run two/multiple instances of `garmin-fetch-data` and initialize them separately anyway (one container can run one user only at a time), I don't see any point keeping them in the same database with a separate tag, better use a separate database altogether - cleaner and better. 

Yet, I will implement what you requested here and close it thereafter.

**Comment by kruemelro** [comment]
Great Work! Thank you very much!
I will have a look and post some screenshots how to use the tag

**Comment by arpanghosh8453** [comment]
@kruemelro Sounds good! Please note that updating the container will only apply that tag on the data it fetches thereafter, and won't apply on data fetched previously (i.e. historic data in the database)

**Comment by bhugh** [comment]
FYI this is the command I used to create a new database:

`docker exec influxdb influx -execute 'CREATE DATABASE GarminStats_spouse'`

Note that I used underline rather than dash, as the dash (_GarminStats-spouse_) gave an error.  There might be some way to properly escape the command to make a dash work but I didn't feel the need to try.

Also, you can accomplish the same thing this way:

`docker exec -it influxdb bash
> influx
>> CREATE DATABASE GarminStats_spouse
>> EXIT
>exit`

The advantage of this second way is while you are inside the database you can run additional commands like `SHOW DATABASES` just to make sure you've got everything right.

Influx v. 1 documentation & basic usage: https://docs.influxdata.com/influxdb/v1/introduction/get-started/

**Comment by arpanghosh8453** [comment]
Hello @bhugh, Thank you so much for the amazing guide! You did solve it very well. I will copy your version and provide a more generic versions without the additional settings applied if someone wants that - with default password and all as original. 

- Good catch on the DB name, It's best to use no special characters, but _ is fine. `-` should not be used in the DB name by all means.

>[!NOTE]
> Anyone trying this out, remember you need to add the following *in addition* to the existing default `garmin-fetch-data` container in the compose stack along with everything else (influxdb and grafana). And you should follow the manual database creation steps [outlined here](https://github.com/arpanghosh8453/garmin-grafana/issues/96#issuecomment-2868627808) before deploying the additional stack. If you don't set the GARMINCONNECT_EMAIL and GARMINCONNECT_BASE64_PASSWORD variables in the compose (or have 2FA enabled for the account), you need to run the password initialization step with docker run for this container separately with `docker compose run --rm  garmin-fetch-data-SPOUSE` before deploying it as a full stack with `docker compose up -d`

```yaml
 garmin-fetch-data-SPOUSE:   ### added -SPOUSE
    restart: unless-stopped
    image: thisisarpanghosh/garmin-fetch-data:latest
    container_name: garmin-fetch-data-SPOUSE   ### added -SPOUSE
    depends-on:
      - influxdb
    volumes:
      - ./garminconnect-tokens-spouse:/home/appuser/.garminconnect   ### need to create new directory garminconnect-tokens-spouse and set appropriate permissions - this change is very important or it will seem to work otherwise but will only pull YOUR data using your tokens instead of your spouse.
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086 
      - INFLUXDB_USERNAME=influxdb_user 
      - INFLUXDB_PASSWORD=influxdb_secret_password
      - INFLUXDB_DATABASE=GarminStats_SPOUSE  ### note added _SPOUSE on DB name - make sure match whatever name you gave the influx DB when creating it
      #####################################################################################
      # - GARMINCONNECT_EMAIL=[[SPOUSE'S EMAIL ADDRESS]]  ### spouse's email
      # - GARMINCONNECT_BASE64_PASSWORD=[[SPOUSE'S GARMIN password BASE64 encoded]] ### spouse's password for garmin connect
```
About adding this to a dashboard, after you add the data source (remember to use the Datasource name as `GarminStats_SPOUSE` instead of `GarminStats` during configuration), you can easily create a new dashboard by exporting the current one (select external export when exporting) as JSON or use the code `23245` for importing a brand new dashboard. Then you can easily select the new database name when importing it (select the new data source you just created for your spouse's data). That would be much easier in my opinion. 

A HUGE thanks to @bhugh for trying this out and documenting this.
